apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - image: busybox
    name: app
    command: 
      - cat
      - /data/id_rsa.pub
    volumeMounts:
    - mountPath: /data
      name: data
  initContainers:
  - image: ramiro/ssh-keygen
    imagePullPolicy: Always
    name: ssh-keygen
    volumeMounts:
    - mountPath: /data
      name: data
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  volumes:
  - name: data
    emptyDir: {}